### ISSUE TITLE
Proxy requests

### ISSUE THREAD

**Issue by ayunami2000** [RealityMoez/openai-chatbot#1]
Hi, I wanna let you know that you should proxy your openai requests, because your openai token is public rn and that is _bad_. People can use it to access OpenAI's API for free, leaving you having to pay for it all.

**Comment by RealityMoez** [comment]
> Hi, I wanna let you know that you should proxy your openai requests, because your openai token is public rn and that is _bad_. People can use it to access OpenAI's API for free, leaving you having to pay for it all.

I store the key in a file, did you saw it? if so can you tell me where privately?
and Thanks for the notice.

**Comment by ayunami2000** [comment]
> > Hi, I wanna let you know that you should proxy your openai requests, because your openai token is public rn and that is _bad_. People can use it to access OpenAI's API for free, leaving you having to pay for it all.
> 
> 
> 
> I store the key in a file, did you saw it? if so can you tell me where privately?
> 
> and Thanks for the notice.

I think the best ways to handle this are to 1) proxy your requests through a server that optionally ratelimits requests, allowing you to have control over API usage as well as hide your API key, 2) disable the functionality of your chat application, perhaps adding in template responses in place of OpenAI responses to demonstrate its' functionality, or 3) (best option imo) have a field for users to input their own OpenAI api key, so that they are the ones who pay to use your chat application, not you, and your API key is kept safe. No matter what you choose, however, you must reset/invalidate your OpenAI API key so that users who have already found it and are potentially using it can no longer use it. You can create a new one, but **do not share it**. I also recommend, at least from what I did, that you set a maximum budget on your OpenAI account, so that in the chance someone does abuse it, it stops working after, say, $16 per month.

Good luck and stay safe on the internet!
